/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { PaymentResponse } from './paymentResponse';
import type { ApiError } from './apiError';

export interface ApiResultPaymentResponse {
  success?: boolean;
  response?: PaymentResponse;
  error?: ApiError;
}
