/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { PaymentFailRequest } from './paymentFailRequest';
import type { ApiError } from './apiError';

export interface ApiResultPaymentFailRequest {
  success?: boolean;
  response?: PaymentFailRequest;
  error?: ApiError;
}
