/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export interface BoardCreateRequest {
  /** title */
  title: string;
  /** subTitle */
  subTitle?: string;
  /** content */
  content: string;
  /** targetAmount */
  targetAmount: number;
  /** endAt */
  endAt: string;
}
