/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { BoardCreateRequest } from './boardCreateRequest';
import type { PlanCreateRequest } from './planCreateRequest';

export type Create1Body = {
  boardCreateRequest: BoardCreateRequest;
  img: Blob;
  planCreatesRequest: PlanCreateRequest[];
};
