/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export type HeartResponseStatus = typeof HeartResponseStatus[keyof typeof HeartResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HeartResponseStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
