/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export type OrderResponsePaymentStatus = typeof OrderResponsePaymentStatus[keyof typeof OrderResponsePaymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponsePaymentStatus = {
  READY: 'READY',
  PAID: 'PAID',
  CANCEL: 'CANCEL',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
} as const;
