/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

/**
 * 결제 타입
 */
export type OrderRequestPayType = typeof OrderRequestPayType[keyof typeof OrderRequestPayType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderRequestPayType = {
  CARD: 'CARD',
  TRANS: 'TRANS',
  VBANK: 'VBANK',
  PHONE: 'PHONE',
} as const;
