/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { OrderRequestPayType } from './orderRequestPayType';

export interface OrderRequest {
  /** 결제 금액 */
  amount: number;
  /** 게시판 id */
  boardId: number;
  /** 결제 타입 */
  payType: OrderRequestPayType;
}
