/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { OrderResponsePayType } from './orderResponsePayType';
import type { OrderResponsePaymentStatus } from './orderResponsePaymentStatus';

export interface OrderResponse {
  payType?: OrderResponsePayType;
  amount?: number;
  orderName?: string;
  customerName?: string;
  customerEmail?: string;
  orderId?: string;
  successUrl?: string;
  failUrl?: string;
  createAt?: string;
  paymentStatus?: OrderResponsePaymentStatus;
}
