/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export interface PageImageGet {
  id?: number;
  title?: string;
  fundraiserId?: number;
  fundraiserName?: string;
  percent?: number;
  imageId?: number;
  imageUrl?: string;
  imageName?: string;
  createdAt?: string;
  endAt?: string;
  fundraiserProfileUrl?: string;
  fundraiserProfileName?: string;
  dday?: number;
}
