/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { CompleteResponse } from './completeResponse';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageCompleteResponse {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: CompleteResponse[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
