/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export interface PaymentResponse {
  boardId?: number;
  customerName?: string;
  customerEmail?: string;
  boardName?: string;
  fundraiserName?: string;
  balanceAmount?: number;
  paymentId?: number;
  orderId?: number;
}
