/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export interface PaymentFailRequest {
  /** 에러코드 */
  errorCode?: string;
  /** 에러메시지 */
  errorMsg?: string;
  /** 주문번호 */
  orderId?: string;
}
