/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

/**
 * ROLE_DONER, ROLE_FUNDRAISER
 */
export type UserCreateRequestRole = typeof UserCreateRequestRole[keyof typeof UserCreateRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreateRequestRole = {
  ROLE_DONER: 'ROLE_DONER',
  ROLE_FUNDRAISER: 'ROLE_FUNDRAISER',
} as const;
