/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { UserResponseRole } from './userResponseRole';
import type { UserResponseStatus } from './userResponseStatus';

export interface UserResponse {
  /** 유저 식별자 */
  id?: number;
  /** 유저 이메일 */
  email?: string;
  /** 유저 이름 */
  name?: string;
  /** 유저 역할 */
  role?: UserResponseRole;
  /** 유저 상태 - 이메일 인증 여부 */
  status?: UserResponseStatus;
}
