/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

export type UserAndProfileResponseRole = typeof UserAndProfileResponseRole[keyof typeof UserAndProfileResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAndProfileResponseRole = {
  ROLE_DONER: 'ROLE_DONER',
  ROLE_FUNDRAISER: 'ROLE_FUNDRAISER',
} as const;
