/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */

/**
 * 유저 역할
 */
export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  ROLE_DONER: 'ROLE_DONER',
  ROLE_FUNDRAISER: 'ROLE_FUNDRAISER',
} as const;
