/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Hi Kitty 프로젝트!!
 * Hi Kitty의 API 명세서입니다.
 * OpenAPI spec version: v1
 */
import type { UserCreateRequestRole } from './userCreateRequestRole';

export interface UserCreateRequest {
  /** 이메일 */
  email: string;
  /** name */
  name: string;
  /** 비밀번호 */
  password: string;
  /** ROLE_DONER, ROLE_FUNDRAISER */
  role: UserCreateRequestRole;
}
